### ISSUE TITLE
Please consider a hosted version

### ISSUE THREAD

**Issue by kyrofa** [snapcore/snap-store-badges#2]
I appreciate having these images available, but at this point they're really only useful for embedding in a website. When it comes to my documentation (e.g. my README), I don't really want to commit images into my repo that don't have anything to do with my software. Please consider hosting these, similar to how various CI systems do it (e.g. Travis) to show build statuses, and perhaps provide a markdown snippet on the snap info page for a quick way to embed it into one's README.

**Comment by therealjuan-zz** [comment]
Thanks for your note. We are currently working on the hosted version for these assets on [the following issue in snapcraft.io](https://github.com/canonical-websites/snapcraft.io/issues/1269) so it's coming soon. 

You would be able to embed a snap from its publisher page where we will be giving you instructions on how to get these assets in their hosted version.

**Comment by brlin-tw** [comment]
[RawGit](https://rawgit.com/) like services can also help.

**Comment by kyrofa** [comment]
Perfect, thanks @therealjuan :) .

**Comment by therealjuan-zz** [comment]
Thanks guys!
